package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 11 11:07:03 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdditionalPOPVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AdditionalPOPVOImpl() {
    }


}
