package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 13 19:10:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BPOLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BPOLOVImpl() {
    }


    /**
     * Returns the bind variable value for p_buyerId.
     * @return bind variable value for p_buyerId
     */
    public String getp_buyerId() {
        return (String)getNamedWhereClauseParam("p_buyerId");
    }

    /**
     * Sets <code>value</code> for bind variable p_buyerId.
     * @param value value to bind as p_buyerId
     */
    public void setp_buyerId(String value) {
        setNamedWhereClauseParam("p_buyerId", value);
    }

    /**
     * Returns the bind variable value for p_style.
     * @return bind variable value for p_style
     */
    public String getp_style() {
        return (String)getNamedWhereClauseParam("p_style");
    }

    /**
     * Sets <code>value</code> for bind variable p_style.
     * @param value value to bind as p_style
     */
    public void setp_style(String value) {
        setNamedWhereClauseParam("p_style", value);
    }

    /**
     * Returns the variable value for p_bpo.
     * @return variable value for p_bpo
     */
    public String getp_bpo() {
        return (String)ensureVariableManager().getVariableValue("p_bpo");
    }

    /**
     * Sets <code>value</code> for variable p_bpo.
     * @param value value to bind as p_bpo
     */
    public void setp_bpo(String value) {
        ensureVariableManager().setVariableValue("p_bpo", value);
    }
}
