package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 13 18:32:25 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BuyerLovVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BuyerLovVoImpl() {
    }
}
