package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 13 17:56:17 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InseemLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InseemLOVImpl() {
    }
}
