package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 13 17:28:11 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class jobLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public jobLOVImpl() {
    }


    /**
     * Returns the variable value for p_job.
     * @return variable value for p_job
     */
    public String getp_job() {
        return (String)ensureVariableManager().getVariableValue("p_job");
    }

    /**
     * Sets <code>value</code> for variable p_job.
     * @param value value to bind as p_job
     */
    public void setp_job(String value) {
        ensureVariableManager().setVariableValue("p_job", value);
    }


    /**
     * Returns the variable value for p_stn.
     * @return variable value for p_stn
     */
    public String getp_stn() {
        return (String)ensureVariableManager().getVariableValue("p_stn");
    }

    /**
     * Sets <code>value</code> for variable p_stn.
     * @param value value to bind as p_stn
     */
    public void setp_stn(String value) {
        ensureVariableManager().setVariableValue("p_stn", value);
    }
}
