package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 14 15:22:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SizeLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SizeLOVImpl() {
    }


    /**
     * Returns the bind variable value for P_HEADER_ID.
     * @return bind variable value for P_HEADER_ID
     */
    public String getP_HEADER_ID() {
        return (String)getNamedWhereClauseParam("P_HEADER_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_HEADER_ID.
     * @param value value to bind as P_HEADER_ID
     */
    public void setP_HEADER_ID(String value) {
        setNamedWhereClauseParam("P_HEADER_ID", value);
    }

    /**
     * Returns the bind variable value for P_LINE_ID.
     * @return bind variable value for P_LINE_ID
     */
    public String getP_LINE_ID() {
        return (String)getNamedWhereClauseParam("P_LINE_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_LINE_ID.
     * @param value value to bind as P_LINE_ID
     */
    public void setP_LINE_ID(String value) {
        setNamedWhereClauseParam("P_LINE_ID", value);
    }


    /**
     * Returns the bind variable value for P_ORG_ID.
     * @return bind variable value for P_ORG_ID
     */
    public String getP_ORG_ID() {
        return (String)getNamedWhereClauseParam("P_ORG_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ORG_ID.
     * @param value value to bind as P_ORG_ID
     */
    public void setP_ORG_ID(String value) {
        setNamedWhereClauseParam("P_ORG_ID", value);
    }
}
