package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 14 15:22:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SizeLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SizeLOVImpl() {
    }


}
