package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 14 15:22:45 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SizeLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SizeLOVImpl() {
    }


    /**
     * Returns the bind variable value for P_HEADER_ID.
     * @return bind variable value for P_HEADER_ID
     */
    public String getP_HEADER_ID() {
        return (String)getNamedWhereClauseParam("P_HEADER_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_HEADER_ID.
     * @param value value to bind as P_HEADER_ID
     */
    public void setP_HEADER_ID(String value) {
        setNamedWhereClauseParam("P_HEADER_ID", value);
    }

    /**
     * Returns the bind variable value for P_LINE_ID.
     * @return bind variable value for P_LINE_ID
     */
    public String getP_LINE_ID() {
        return (String)getNamedWhereClauseParam("P_LINE_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_LINE_ID.
     * @param value value to bind as P_LINE_ID
     */
    public void setP_LINE_ID(String value) {
        setNamedWhereClauseParam("P_LINE_ID", value);
    }

    /**
     * Returns the bind variable value for p_Org_Id.
     * @return bind variable value for p_Org_Id
     */
    public String getp_Org_Id() {
        return (String)getNamedWhereClauseParam("p_Org_Id");
    }

    /**
     * Sets <code>value</code> for bind variable p_Org_Id.
     * @param value value to bind as p_Org_Id
     */
    public void setp_Org_Id(String value) {
        setNamedWhereClauseParam("p_Org_Id", value);
    }
}
