package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 13 19:20:58 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class STNLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public STNLOVImpl() {
    }


    /**
     * Returns the bind variable value for p_headerId.
     * @return bind variable value for p_headerId
     */
    public String getp_headerId() {
        return (String)getNamedWhereClauseParam("p_headerId");
    }

    /**
     * Sets <code>value</code> for bind variable p_headerId.
     * @param value value to bind as p_headerId
     */
    public void setp_headerId(String value) {
        setNamedWhereClauseParam("p_headerId", value);
    }

    /**
     * Returns the variable value for STN.
     * @return variable value for STN
     */
    public String getSTN() {
        return (String)ensureVariableManager().getVariableValue("STN");
    }

    /**
     * Sets <code>value</code> for variable STN.
     * @param value value to bind as STN
     */
    public void setSTN(String value) {
        ensureVariableManager().setVariableValue("STN", value);
    }

    /**
     * Returns the bind variable value for p_Org_Id.
     * @return bind variable value for p_Org_Id
     */
    public String getp_Org_Id() {
        return (String)getNamedWhereClauseParam("p_Org_Id");
    }

    /**
     * Sets <code>value</code> for bind variable p_Org_Id.
     * @param value value to bind as p_Org_Id
     */
    public void setp_Org_Id(String value) {
        setNamedWhereClauseParam("p_Org_Id", value);
    }
}
