package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 13 18:46:20 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StyleLovImpl() {
    }


    /**
     * Returns the bind variable value for p_customerID.
     * @return bind variable value for p_customerID
     */
    public String getp_customerID() {
        return (String)getNamedWhereClauseParam("p_customerID");
    }

    /**
     * Sets <code>value</code> for bind variable p_customerID.
     * @param value value to bind as p_customerID
     */
    public void setp_customerID(String value) {
        setNamedWhereClauseParam("p_customerID", value);
    }

    /**
     * Returns the variable value for style_name.
     * @return variable value for style_name
     */
    public String getstyle_name() {
        return (String)ensureVariableManager().getVariableValue("style_name");
    }

    /**
     * Sets <code>value</code> for variable style_name.
     * @param value value to bind as style_name
     */
    public void setstyle_name(String value) {
        ensureVariableManager().setVariableValue("style_name", value);
    }

    /**
     * Returns the variable value for Style_no.
     * @return variable value for Style_no
     */
    public String getStyle_no() {
        return (String)ensureVariableManager().getVariableValue("Style_no");
    }

    /**
     * Sets <code>value</code> for variable Style_no.
     * @param value value to bind as Style_no
     */
    public void setStyle_no(String value) {
        ensureVariableManager().setVariableValue("Style_no", value);
    }
}
