package mnj.ont.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 13 18:46:20 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleLovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BpoNo {
            public Object get(StyleLovRowImpl obj) {
                return obj.getBpoNo();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        OrderNumber {
            public Object get(StyleLovRowImpl obj) {
                return obj.getOrderNumber();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setOrderNumber((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(StyleLovRowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(StyleLovRowImpl obj) {
                return obj.getOrgId();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        CustomerName {
            public Object get(StyleLovRowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        StyleName {
            public Object get(StyleLovRowImpl obj) {
                return obj.getStyleName();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        StyleNo {
            public Object get(StyleLovRowImpl obj) {
                return obj.getStyleNo();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setStyleNo((String)value);
            }
        }
        ,
        Brand {
            public Object get(StyleLovRowImpl obj) {
                return obj.getBrand();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        Season {
            public Object get(StyleLovRowImpl obj) {
                return obj.getSeason();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Fit {
            public Object get(StyleLovRowImpl obj) {
                return obj.getFit();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setFit((String)value);
            }
        }
        ,
        EndUser {
            public Object get(StyleLovRowImpl obj) {
                return obj.getEndUser();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setEndUser((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(StyleLovRowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        OrderedQty {
            public Object get(StyleLovRowImpl obj) {
                return obj.getOrderedQty();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setOrderedQty((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(StyleLovRowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(StyleLovRowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StyleLovRowImpl object);

        public abstract void put(StyleLovRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int ORDERNUMBER = AttributesEnum.OrderNumber.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int STYLENO = AttributesEnum.StyleNo.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int FIT = AttributesEnum.Fit.index();
    public static final int ENDUSER = AttributesEnum.EndUser.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ORDEREDQTY = AttributesEnum.OrderedQty.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StyleLovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BpoNo.
     * @return the BpoNo
     */
    public String getBpoNo() {
        return (String) getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BpoNo.
     * @param value value to set the  BpoNo
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderNumber.
     * @return the OrderNumber
     */
    public Number getOrderNumber() {
        return (Number) getAttributeInternal(ORDERNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber.
     * @param value value to set the  OrderNumber
     */
    public void setOrderNumber(Number value) {
        setAttributeInternal(ORDERNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgId.
     * @param value value to set the  OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleName.
     * @return the StyleName
     */
    public String getStyleName() {
        return (String) getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleName.
     * @param value value to set the  StyleName
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleNo.
     * @return the StyleNo
     */
    public String getStyleNo() {
        return (String) getAttributeInternal(STYLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleNo.
     * @param value value to set the  StyleNo
     */
    public void setStyleNo(String value) {
        setAttributeInternal(STYLENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Brand.
     * @return the Brand
     */
    public String getBrand() {
        return (String) getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Brand.
     * @param value value to set the  Brand
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Fit.
     * @return the Fit
     */
    public String getFit() {
        return (String) getAttributeInternal(FIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Fit.
     * @param value value to set the  Fit
     */
    public void setFit(String value) {
        setAttributeInternal(FIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EndUser.
     * @return the EndUser
     */
    public String getEndUser() {
        return (String) getAttributeInternal(ENDUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndUser.
     * @param value value to set the  EndUser
     */
    public void setEndUser(String value) {
        setAttributeInternal(ENDUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemDescription.
     * @return the ItemDescription
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemDescription.
     * @param value value to set the  ItemDescription
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderedQty.
     * @return the OrderedQty
     */
    public Number getOrderedQty() {
        return (Number) getAttributeInternal(ORDEREDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderedQty.
     * @param value value to set the  OrderedQty
     */
    public void setOrderedQty(Number value) {
        setAttributeInternal(ORDEREDQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerId.
     * @param value value to set the  CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
