package mnj.ont.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 15 12:48:59 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProdTypeNewVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProdTypeNewVoImpl() {
    }

    /**
     * Returns the bind variable value for P_STYLE.
     * @return bind variable value for P_STYLE
     */
    public String getP_STYLE() {
        return (String)getNamedWhereClauseParam("P_STYLE");
    }

    /**
     * Sets <code>value</code> for bind variable P_STYLE.
     * @param value value to bind as P_STYLE
     */
    public void setP_STYLE(String value) {
        setNamedWhereClauseParam("P_STYLE", value);
    }

    /**
     * Returns the bind variable value for P_SEASON.
     * @return bind variable value for P_SEASON
     */
    public String getP_SEASON() {
        return (String)getNamedWhereClauseParam("P_SEASON");
    }

    /**
     * Sets <code>value</code> for bind variable P_SEASON.
     * @param value value to bind as P_SEASON
     */
    public void setP_SEASON(String value) {
        setNamedWhereClauseParam("P_SEASON", value);
    }

    /**
     * Returns the bind variable value for P_BUYER_ID.
     * @return bind variable value for P_BUYER_ID
     */
    public String getP_BUYER_ID() {
        return (String)getNamedWhereClauseParam("P_BUYER_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_BUYER_ID.
     * @param value value to bind as P_BUYER_ID
     */
    public void setP_BUYER_ID(String value) {
        setNamedWhereClauseParam("P_BUYER_ID", value);
    }

    /**
     * Returns the bind variable value for P_COLOR.
     * @return bind variable value for P_COLOR
     */
    public String getP_COLOR() {
        return (String)getNamedWhereClauseParam("P_COLOR");
    }

    /**
     * Sets <code>value</code> for bind variable P_COLOR.
     * @param value value to bind as P_COLOR
     */
    public void setP_COLOR(String value) {
        setNamedWhereClauseParam("P_COLOR", value);
    }
}
