package mnj.ont.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 15 12:48:59 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProdTypeNewVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProdTypeNewVoImpl() {
    }


    /**
     * Returns the bind variable value for P_SYSTEM_ID.
     * @return bind variable value for P_SYSTEM_ID
     */
    public String getP_SYSTEM_ID() {
        return (String)getNamedWhereClauseParam("P_SYSTEM_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_SYSTEM_ID.
     * @param value value to bind as P_SYSTEM_ID
     */
    public void setP_SYSTEM_ID(String value) {
        setNamedWhereClauseParam("P_SYSTEM_ID", value);
    }
}
