package mnj.ont.model.services.client;

import mnj.ont.model.services.common.InquiryInfoAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 14 14:30:00 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InquiryInfoAMClient extends ApplicationModuleImpl implements InquiryInfoAM {
    /**
     * This is the default constructor (do not remove).
     */
    public InquiryInfoAMClient() {
    }


    public int sumtotalRejectiondetail() {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalRejectiondetail",null,null);
        return ((Integer)_ret).intValue();
    }


    public int sumtotalProduction(String ProdTransId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalProduction",new String [] {"java.lang.String"},new Object[] {ProdTransId});
        return ((Integer)_ret).intValue();
    }


    public double GET_TOTAL_SAM(int p_header_id) {
        Object _ret =
            this.riInvokeExportedMethod(this,"GET_TOTAL_SAM",new String [] {"int"},new Object[] {new Integer(p_header_id)});
        return ((Double)_ret).doubleValue();
    }


    public String completion(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"completion",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }


    public String callPost(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"callPost",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public void FillLines() {
        Object _ret = this.riInvokeExportedMethod(this,"FillLines",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void FillSizes() {
        Object _ret = this.riInvokeExportedMethod(this,"FillSizes",null,null);
        return;
    }

    public void setSizeWherCaluse() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSizeWherCaluse",null,null);
        return;
    }

    public int sumtotalRejectiondetail(String OutSublineId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalRejectiondetail",new String [] {"java.lang.String"},new Object[] {OutSublineId});
        return ((Integer)_ret).intValue();
    }

    public int sumtotalprodetail(String OutSublineId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalprodetail",new String [] {"java.lang.String"},new Object[] {OutSublineId});
        return ((Integer)_ret).intValue();
    }

    public int sumtotalProductionWIPLINE(String ProdTransId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalProductionWIPLINE",new String [] {"java.lang.String"},new Object[] {ProdTransId});
        return ((Integer)_ret).intValue();
    }

    public int sumtotalprodetailWIP(String OutSublineId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalprodetailWIP",new String [] {"java.lang.String"},new Object[] {OutSublineId});
        return ((Integer)_ret).intValue();
    }

    public int sumtotalProduction() {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalProduction",null,null);
        return ((Integer)_ret).intValue();
    }

    public int sumtotalRejection() {
        Object _ret =
            this.riInvokeExportedMethod(this,"sumtotalRejection",null,null);
        return ((Integer)_ret).intValue();
    }

    public String CalculateTotalProductionNewLINE(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CalculateTotalProductionNewLINE",new String [] {"java.lang.String"},new Object[] {headerId});
        return (String)_ret;
    }

    public void ExecuteBlock() {
        Object _ret = this.riInvokeExportedMethod(this,"ExecuteBlock",null,null);
        return;
    }

    public void setSizeWherCaluseNew() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSizeWherCaluseNew",null,null);
        return;
    }

    public void FillLinesNEW() {
        Object _ret = this.riInvokeExportedMethod(this,"FillLinesNEW",null,null);
        return;
    }

    public void FillLinesNEWTab() {
        Object _ret =
            this.riInvokeExportedMethod(this,"FillLinesNEWTab",null,null);
        return;
    }

    public void selectAllLines(String FlagNEWTab) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines",new String [] {"java.lang.String"},new Object[] {FlagNEWTab});
        return;
    }

    public double GET_TOTAL_MINUTS(int p_header_id) {
        Object _ret =
            this.riInvokeExportedMethod(this,"GET_TOTAL_MINUTS",new String [] {"int"},new Object[] {new Integer(p_header_id)});
        return ((Double)_ret).doubleValue();
    }

    public String completion(String headerId, String respId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"completion",new String [] {"java.lang.String","java.lang.String"},new Object[] {headerId, respId});
        return (String)_ret;
    }
}
