package mnj.ont.model.views;

import mnj.ont.model.entities.DetailEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 25 16:13:42 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(DetailVORowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        ProdTransId {
            public Object get(DetailVORowImpl obj) {
                return obj.getProdTransId();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setProdTransId((Number)value);
            }
        }
        ,
        OutSublineId {
            public Object get(DetailVORowImpl obj) {
                return obj.getOutSublineId();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setOutSublineId((Number)value);
            }
        }
        ,
        DetailId {
            public Object get(DetailVORowImpl obj) {
                return obj.getDetailId();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        ProductionQuantity {
            public Object get(DetailVORowImpl obj) {
                return obj.getProductionQuantity();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setProductionQuantity((String)value);
            }
        }
        ,
        ProdQty {
            public Object get(DetailVORowImpl obj) {
                return obj.getProdQty();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setProdQty((String)value);
            }
        }
        ,
        Cutqty {
            public Object get(DetailVORowImpl obj) {
                return obj.getCutqty();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setCutqty((Number)value);
            }
        }
        ,
        Rejection {
            public Object get(DetailVORowImpl obj) {
                return obj.getRejection();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setRejection((Number)value);
            }
        }
        ,
        SizeVal {
            public Object get(DetailVORowImpl obj) {
                return obj.getSizeVal();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setSizeVal((String)value);
            }
        }
        ,
        PrevProdQty {
            public Object get(DetailVORowImpl obj) {
                return obj.getPrevProdQty();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setPrevProdQty((Number)value);
            }
        }
        ,
        TotalInput {
            public Object get(DetailVORowImpl obj) {
                return obj.getTotalInput();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setTotalInput((Number)value);
            }
        }
        ,
        DayProoduction {
            public Object get(DetailVORowImpl obj) {
                return obj.getDayProoduction();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setDayProoduction((Number)value);
            }
        }
        ,
        TotalProduction {
            public Object get(DetailVORowImpl obj) {
                return obj.getTotalProduction();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setTotalProduction((Number)value);
            }
        }
        ,
        TotalRejection {
            public Object get(DetailVORowImpl obj) {
                return obj.getTotalRejection();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setTotalRejection((Number)value);
            }
        }
        ,
        Inseem {
            public Object get(DetailVORowImpl obj) {
                return obj.getInseem();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setInseem((String)value);
            }
        }
        ,
        Wip {
            public Object get(DetailVORowImpl obj) {
                return obj.getWip();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setWip((Number)value);
            }
        }
        ,
        R1 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR1();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR1((Number)value);
            }
        }
        ,
        R2 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR2();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR2((Number)value);
            }
        }
        ,
        R3 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR3();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR3((Number)value);
            }
        }
        ,
        R4 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR4();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR4((Number)value);
            }
        }
        ,
        R5 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR5();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR5((Number)value);
            }
        }
        ,
        R6 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR6();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR6((Number)value);
            }
        }
        ,
        R7 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR7();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR7((Number)value);
            }
        }
        ,
        R8 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR8();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR8((Number)value);
            }
        }
        ,
        R9 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR9();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR9((Number)value);
            }
        }
        ,
        R10 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR10();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR10((Number)value);
            }
        }
        ,
        R11 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR11();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR11((Number)value);
            }
        }
        ,
        R12 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR12();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR12((Number)value);
            }
        }
        ,
        R13 {
            public Object get(DetailVORowImpl obj) {
                return obj.getR13();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setR13((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DetailVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(DetailVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(DetailVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(DetailVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        SizeLOV1 {
            public Object get(DetailVORowImpl obj) {
                return obj.getSizeLOV1();
            }

            public void put(DetailVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DetailVORowImpl object);

        public abstract void put(DetailVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int PRODTRANSID = AttributesEnum.ProdTransId.index();
    public static final int OUTSUBLINEID = AttributesEnum.OutSublineId.index();
    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int PRODUCTIONQUANTITY = AttributesEnum.ProductionQuantity.index();
    public static final int PRODQTY = AttributesEnum.ProdQty.index();
    public static final int CUTQTY = AttributesEnum.Cutqty.index();
    public static final int REJECTION = AttributesEnum.Rejection.index();
    public static final int SIZEVAL = AttributesEnum.SizeVal.index();
    public static final int PREVPRODQTY = AttributesEnum.PrevProdQty.index();
    public static final int TOTALINPUT = AttributesEnum.TotalInput.index();
    public static final int DAYPROODUCTION = AttributesEnum.DayProoduction.index();
    public static final int TOTALPRODUCTION = AttributesEnum.TotalProduction.index();
    public static final int TOTALREJECTION = AttributesEnum.TotalRejection.index();
    public static final int INSEEM = AttributesEnum.Inseem.index();
    public static final int WIP = AttributesEnum.Wip.index();
    public static final int R1 = AttributesEnum.R1.index();
    public static final int R2 = AttributesEnum.R2.index();
    public static final int R3 = AttributesEnum.R3.index();
    public static final int R4 = AttributesEnum.R4.index();
    public static final int R5 = AttributesEnum.R5.index();
    public static final int R6 = AttributesEnum.R6.index();
    public static final int R7 = AttributesEnum.R7.index();
    public static final int R8 = AttributesEnum.R8.index();
    public static final int R9 = AttributesEnum.R9.index();
    public static final int R10 = AttributesEnum.R10.index();
    public static final int R11 = AttributesEnum.R11.index();
    public static final int R12 = AttributesEnum.R12.index();
    public static final int R13 = AttributesEnum.R13.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int SIZELOV1 = AttributesEnum.SizeLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DetailVORowImpl() {
    }

    /**
     * Gets DetailEO entity object.
     * @return the DetailEO
     */
    public DetailEOImpl getDetailEO() {
        return (DetailEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for PROD_TRANS_ID using the alias name ProdTransId.
     * @return the PROD_TRANS_ID
     */
    public Number getProdTransId() {
        return (Number) getAttributeInternal(PRODTRANSID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_TRANS_ID using the alias name ProdTransId.
     * @param value value to set the PROD_TRANS_ID
     */
    public void setProdTransId(Number value) {
        setAttributeInternal(PRODTRANSID, value);
    }

    /**
     * Gets the attribute value for OUT_SUBLINE_ID using the alias name OutSublineId.
     * @return the OUT_SUBLINE_ID
     */
    public Number getOutSublineId() {
        return (Number) getAttributeInternal(OUTSUBLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for OUT_SUBLINE_ID using the alias name OutSublineId.
     * @param value value to set the OUT_SUBLINE_ID
     */
    public void setOutSublineId(Number value) {
        setAttributeInternal(OUTSUBLINEID, value);
    }

    /**
     * Gets the attribute value for DETAIL_ID using the alias name DetailId.
     * @return the DETAIL_ID
     */
    public Number getDetailId() {
        return (Number) getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL_ID using the alias name DetailId.
     * @param value value to set the DETAIL_ID
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_QUANTITY using the alias name ProductionQuantity.
     * @return the PRODUCTION_QUANTITY
     */
    public String getProductionQuantity() {
        return (String) getAttributeInternal(PRODUCTIONQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_QUANTITY using the alias name ProductionQuantity.
     * @param value value to set the PRODUCTION_QUANTITY
     */
    public void setProductionQuantity(String value) {
        setAttributeInternal(PRODUCTIONQUANTITY, value);
    }

    /**
     * Gets the attribute value for PROD_QTY using the alias name ProdQty.
     * @return the PROD_QTY
     */
    public String getProdQty() {
        return (String) getAttributeInternal(PRODQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_QTY using the alias name ProdQty.
     * @param value value to set the PROD_QTY
     */
    public void setProdQty(String value) {
        setAttributeInternal(PRODQTY, value);
    }

    /**
     * Gets the attribute value for CUTQTY using the alias name Cutqty.
     * @return the CUTQTY
     */
    public Number getCutqty() {
        return (Number) getAttributeInternal(CUTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for CUTQTY using the alias name Cutqty.
     * @param value value to set the CUTQTY
     */
    public void setCutqty(Number value) {
        setAttributeInternal(CUTQTY, value);
    }

    /**
     * Gets the attribute value for REJECTION using the alias name Rejection.
     * @return the REJECTION
     */
    public Number getRejection() {
        return (Number) getAttributeInternal(REJECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECTION using the alias name Rejection.
     * @param value value to set the REJECTION
     */
    public void setRejection(Number value) {
        setAttributeInternal(REJECTION, value);
    }

    /**
     * Gets the attribute value for SIZE_VAL using the alias name SizeVal.
     * @return the SIZE_VAL
     */
    public String getSizeVal() {
        return (String) getAttributeInternal(SIZEVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_VAL using the alias name SizeVal.
     * @param value value to set the SIZE_VAL
     */
    public void setSizeVal(String value) {
        setAttributeInternal(SIZEVAL, value);
    }

    /**
     * Gets the attribute value for PREV_PROD_QTY using the alias name PrevProdQty.
     * @return the PREV_PROD_QTY
     */
    public Number getPrevProdQty() {
        return (Number) getAttributeInternal(PREVPRODQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PREV_PROD_QTY using the alias name PrevProdQty.
     * @param value value to set the PREV_PROD_QTY
     */
    public void setPrevProdQty(Number value) {
        setAttributeInternal(PREVPRODQTY, value);
    }

    /**
     * Gets the attribute value for TOTAL_INPUT using the alias name TotalInput.
     * @return the TOTAL_INPUT
     */
    public Number getTotalInput() {
        return (Number) getAttributeInternal(TOTALINPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_INPUT using the alias name TotalInput.
     * @param value value to set the TOTAL_INPUT
     */
    public void setTotalInput(Number value) {
        setAttributeInternal(TOTALINPUT, value);
    }

    /**
     * Gets the attribute value for DAY_PROODUCTION using the alias name DayProoduction.
     * @return the DAY_PROODUCTION
     */
    public Number getDayProoduction() {
        return (Number) getAttributeInternal(DAYPROODUCTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY_PROODUCTION using the alias name DayProoduction.
     * @param value value to set the DAY_PROODUCTION
     */
    public void setDayProoduction(Number value) {
        setAttributeInternal(DAYPROODUCTION, value);
    }

    /**
     * Gets the attribute value for TOTAL_PRODUCTION using the alias name TotalProduction.
     * @return the TOTAL_PRODUCTION
     */
    public Number getTotalProduction() {
        return (Number) getAttributeInternal(TOTALPRODUCTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_PRODUCTION using the alias name TotalProduction.
     * @param value value to set the TOTAL_PRODUCTION
     */
    public void setTotalProduction(Number value) {
        setAttributeInternal(TOTALPRODUCTION, value);
    }

    /**
     * Gets the attribute value for TOTAL_REJECTION using the alias name TotalRejection.
     * @return the TOTAL_REJECTION
     */
    public Number getTotalRejection() {
        return (Number) getAttributeInternal(TOTALREJECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_REJECTION using the alias name TotalRejection.
     * @param value value to set the TOTAL_REJECTION
     */
    public void setTotalRejection(Number value) {
        setAttributeInternal(TOTALREJECTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wip.
     * @return the Wip
     */
    public Number getWip() {
        return (Number) getAttributeInternal(WIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wip.
     * @param value value to set the  Wip
     */
    public void setWip(Number value) {
        setAttributeInternal(WIP, value);
    }

    /**
     * Gets the attribute value for R1 using the alias name R1.
     * @return the R1
     */
    public Number getR1() {
        return (Number) getAttributeInternal(R1);
    }

    /**
     * Sets <code>value</code> as attribute value for R1 using the alias name R1.
     * @param value value to set the R1
     */
    public void setR1(Number value) {
        setAttributeInternal(R1, value);
    }

    /**
     * Gets the attribute value for R2 using the alias name R2.
     * @return the R2
     */
    public Number getR2() {
        return (Number) getAttributeInternal(R2);
    }

    /**
     * Sets <code>value</code> as attribute value for R2 using the alias name R2.
     * @param value value to set the R2
     */
    public void setR2(Number value) {
        setAttributeInternal(R2, value);
    }

    /**
     * Gets the attribute value for R3 using the alias name R3.
     * @return the R3
     */
    public Number getR3() {
        return (Number) getAttributeInternal(R3);
    }

    /**
     * Sets <code>value</code> as attribute value for R3 using the alias name R3.
     * @param value value to set the R3
     */
    public void setR3(Number value) {
        setAttributeInternal(R3, value);
    }

    /**
     * Gets the attribute value for R4 using the alias name R4.
     * @return the R4
     */
    public Number getR4() {
        return (Number) getAttributeInternal(R4);
    }

    /**
     * Sets <code>value</code> as attribute value for R4 using the alias name R4.
     * @param value value to set the R4
     */
    public void setR4(Number value) {
        setAttributeInternal(R4, value);
    }

    /**
     * Gets the attribute value for R5 using the alias name R5.
     * @return the R5
     */
    public Number getR5() {
        return (Number) getAttributeInternal(R5);
    }

    /**
     * Sets <code>value</code> as attribute value for R5 using the alias name R5.
     * @param value value to set the R5
     */
    public void setR5(Number value) {
        setAttributeInternal(R5, value);
    }

    /**
     * Gets the attribute value for R6 using the alias name R6.
     * @return the R6
     */
    public Number getR6() {
        return (Number) getAttributeInternal(R6);
    }

    /**
     * Sets <code>value</code> as attribute value for R6 using the alias name R6.
     * @param value value to set the R6
     */
    public void setR6(Number value) {
        setAttributeInternal(R6, value);
    }

    /**
     * Gets the attribute value for R7 using the alias name R7.
     * @return the R7
     */
    public Number getR7() {
        return (Number) getAttributeInternal(R7);
    }

    /**
     * Sets <code>value</code> as attribute value for R7 using the alias name R7.
     * @param value value to set the R7
     */
    public void setR7(Number value) {
        setAttributeInternal(R7, value);
    }

    /**
     * Gets the attribute value for R8 using the alias name R8.
     * @return the R8
     */
    public Number getR8() {
        return (Number) getAttributeInternal(R8);
    }

    /**
     * Sets <code>value</code> as attribute value for R8 using the alias name R8.
     * @param value value to set the R8
     */
    public void setR8(Number value) {
        setAttributeInternal(R8, value);
    }

    /**
     * Gets the attribute value for R9 using the alias name R9.
     * @return the R9
     */
    public Number getR9() {
        return (Number) getAttributeInternal(R9);
    }

    /**
     * Sets <code>value</code> as attribute value for R9 using the alias name R9.
     * @param value value to set the R9
     */
    public void setR9(Number value) {
        setAttributeInternal(R9, value);
    }

    /**
     * Gets the attribute value for R10 using the alias name R10.
     * @return the R10
     */
    public Number getR10() {
        return (Number) getAttributeInternal(R10);
    }

    /**
     * Sets <code>value</code> as attribute value for R10 using the alias name R10.
     * @param value value to set the R10
     */
    public void setR10(Number value) {
        setAttributeInternal(R10, value);
    }

    /**
     * Gets the attribute value for R11 using the alias name R11.
     * @return the R11
     */
    public Number getR11() {
        return (Number) getAttributeInternal(R11);
    }

    /**
     * Sets <code>value</code> as attribute value for R11 using the alias name R11.
     * @param value value to set the R11
     */
    public void setR11(Number value) {
        setAttributeInternal(R11, value);
    }

    /**
     * Gets the attribute value for R12 using the alias name R12.
     * @return the R12
     */
    public Number getR12() {
        return (Number) getAttributeInternal(R12);
    }

    /**
     * Sets <code>value</code> as attribute value for R12 using the alias name R12.
     * @param value value to set the R12
     */
    public void setR12(Number value) {
        setAttributeInternal(R12, value);
    }

    /**
     * Gets the attribute value for R13 using the alias name R13.
     * @return the R13
     */
    public Number getR13() {
        return (Number) getAttributeInternal(R13);
    }

    /**
     * Sets <code>value</code> as attribute value for R13 using the alias name R13.
     * @param value value to set the R13
     */
    public void setR13(Number value) {
        setAttributeInternal(R13, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for INSEEM using the alias name Inseem.
     * @return the INSEEM
     */
    public String getInseem() {
        return (String) getAttributeInternal(INSEEM);
    }

    /**
     * Sets <code>value</code> as attribute value for INSEEM using the alias name Inseem.
     * @param value value to set the INSEEM
     */
    public void setInseem(String value) {
        setAttributeInternal(INSEEM, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SizeLOV1.
     */
    public RowSet getSizeLOV1() {
        return (RowSet)getAttributeInternal(SIZELOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
