package mnj.ont.model.views;

import mnj.ont.model.entities.LineEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 14 15:41:17 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LineVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(LineVORowImpl obj) {
                return obj.getDivisionId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        ProdTransId {
            public Object get(LineVORowImpl obj) {
                return obj.getProdTransId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setProdTransId((Number)value);
            }
        }
        ,
        OutSublineId {
            public Object get(LineVORowImpl obj) {
                return obj.getOutSublineId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setOutSublineId((Number)value);
            }
        }
        ,
        Sno {
            public Object get(LineVORowImpl obj) {
                return obj.getSno();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSno((Number)value);
            }
        }
        ,
        LineId {
            public Object get(LineVORowImpl obj) {
                return obj.getLineId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setLineId((String)value);
            }
        }
        ,
        SublineType {
            public Object get(LineVORowImpl obj) {
                return obj.getSublineType();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSublineType((String)value);
            }
        }
        ,
        NoMachines {
            public Object get(LineVORowImpl obj) {
                return obj.getNoMachines();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setNoMachines((Number)value);
            }
        }
        ,
        SublineNo {
            public Object get(LineVORowImpl obj) {
                return obj.getSublineNo();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSublineNo((String)value);
            }
        }
        ,
        OperatorAbs {
            public Object get(LineVORowImpl obj) {
                return obj.getOperatorAbs();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setOperatorAbs((Number)value);
            }
        }
        ,
        LineOutput {
            public Object get(LineVORowImpl obj) {
                return obj.getLineOutput();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setLineOutput((Number)value);
            }
        }
        ,
        TargetQty {
            public Object get(LineVORowImpl obj) {
                return obj.getTargetQty();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setTargetQty((Number)value);
            }
        }
        ,
        BalanceQty {
            public Object get(LineVORowImpl obj) {
                return obj.getBalanceQty();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBalanceQty((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(LineVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(LineVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(LineVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(LineVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(LineVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        TempQty {
            public Object get(LineVORowImpl obj) {
                return obj.getTempQty();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setTempQty((Number)value);
            }
        }
        ,
        ResPost {
            public Object get(LineVORowImpl obj) {
                return obj.getResPost();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setResPost((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(LineVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(LineVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SizeQuantity {
            public Object get(LineVORowImpl obj) {
                return obj.getSizeQuantity();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSizeQuantity((Number)value);
            }
        }
        ,
        ProdQty {
            public Object get(LineVORowImpl obj) {
                return obj.getProdQty();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setProdQty((String)value);
            }
        }
        ,
        ProductionQuantity {
            public Object get(LineVORowImpl obj) {
                return obj.getProductionQuantity();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setProductionQuantity((String)value);
            }
        }
        ,
        PrvLineoutput {
            public Object get(LineVORowImpl obj) {
                return obj.getPrvLineoutput();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setPrvLineoutput((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(LineVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BpoNo {
            public Object get(LineVORowImpl obj) {
                return obj.getBpoNo();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBpoNo((String)value);
            }
        }
        ,
        SaleOrderId {
            public Object get(LineVORowImpl obj) {
                return obj.getSaleOrderId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSaleOrderId((Number)value);
            }
        }
        ,
        Style {
            public Object get(LineVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(LineVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        JobId {
            public Object get(LineVORowImpl obj) {
                return obj.getJobId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        ErrorMessage {
            public Object get(LineVORowImpl obj) {
                return obj.getErrorMessage();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setErrorMessage((String)value);
            }
        }
        ,
        LastAction {
            public Object get(LineVORowImpl obj) {
                return obj.getLastAction();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setLastAction((String)value);
            }
        }
        ,
        BuyerName {
            public Object get(LineVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        ProdType {
            public Object get(LineVORowImpl obj) {
                return obj.getProdType();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setProdType((String)value);
            }
        }
        ,
        TotRejection {
            public Object get(LineVORowImpl obj) {
                return obj.getTotRejection();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setTotRejection((Number)value);
            }
        }
        ,
        DayRejection {
            public Object get(LineVORowImpl obj) {
                return obj.getDayRejection();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setDayRejection((Number)value);
            }
        }
        ,
        StnNumber {
            public Object get(LineVORowImpl obj) {
                return obj.getStnNumber();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setStnNumber((String)value);
            }
        }
        ,
        JobName {
            public Object get(LineVORowImpl obj) {
                return obj.getJobName();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setJobName((String)value);
            }
        }
        ,
        DayProduction {
            public Object get(LineVORowImpl obj) {
                return obj.getDayProduction();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setDayProduction((Number)value);
            }
        }
        ,
        TotalProduetion {
            public Object get(LineVORowImpl obj) {
                return obj.getTotalProduetion();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setTotalProduetion((Number)value);
            }
        }
        ,
        TotalInput {
            public Object get(LineVORowImpl obj) {
                return obj.getTotalInput();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setTotalInput((Number)value);
            }
        }
        ,
        Wip {
            public Object get(LineVORowImpl obj) {
                return obj.getWip();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setWip((Number)value);
            }
        }
        ,
        PreLineoutput {
            public Object get(LineVORowImpl obj) {
                return obj.getPreLineoutput();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setPreLineoutput((Number)value);
            }
        }
        ,
        Color {
            public Object get(LineVORowImpl obj) {
                return obj.getColor();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        Wash {
            public Object get(LineVORowImpl obj) {
                return obj.getWash();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        ProducedMin {
            public Object get(LineVORowImpl obj) {
                return obj.getProducedMin();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setProducedMin((Number)value);
            }
        }
        ,
        SamValue {
            public Object get(LineVORowImpl obj) {
                return obj.getSamValue();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSamValue((Number)value);
            }
        }
        ,
        Sam {
            public Object get(LineVORowImpl obj) {
                return obj.getSam();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSam((Number)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(LineVORowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(LineVORowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ,
        TotalPro {
            public Object get(LineVORowImpl obj) {
                return obj.getTotalPro();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setTotalPro((Number)value);
            }
        }
        ,
        PrevTotalPro {
            public Object get(LineVORowImpl obj) {
                return obj.getPrevTotalPro();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setPrevTotalPro((Number)value);
            }
        }
        ,
        PrvTargetqty {
            public Object get(LineVORowImpl obj) {
                return obj.getPrvTargetqty();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setPrvTargetqty((String)value);
            }
        }
        ,
        BalanceOutput {
            public Object get(LineVORowImpl obj) {
                return obj.getBalanceOutput();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBalanceOutput((String)value);
            }
        }
        ,
        BalanceTarget {
            public Object get(LineVORowImpl obj) {
                return obj.getBalanceTarget();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBalanceTarget((String)value);
            }
        }
        ,
        OperationLine {
            public Object get(LineVORowImpl obj) {
                return obj.getOperationLine();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setOperationLine((String)value);
            }
        }
        ,
        StnNo {
            public Object get(LineVORowImpl obj) {
                return obj.getStnNo();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setStnNo((String)value);
            }
        }
        ,
        BpoId {
            public Object get(LineVORowImpl obj) {
                return obj.getBpoId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(LineVORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        DetailVO {
            public Object get(LineVORowImpl obj) {
                return obj.getDetailVO();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SizeLOV1 {
            public Object get(LineVORowImpl obj) {
                return obj.getSizeLOV1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LineNoCodeVO1 {
            public Object get(LineVORowImpl obj) {
                return obj.getLineNoCodeVO1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerLovVo1 {
            public Object get(LineVORowImpl obj) {
                return obj.getBuyerLovVo1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdTypeVO1 {
            public Object get(LineVORowImpl obj) {
                return obj.getProdTypeVO1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdTypeNewVo1 {
            public Object get(LineVORowImpl obj) {
                return obj.getProdTypeNewVo1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Sam_LOV1 {
            public Object get(LineVORowImpl obj) {
                return obj.getSam_LOV1();
            }

            public void put(LineVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LineVORowImpl object);

        public abstract void put(LineVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int PRODTRANSID = AttributesEnum.ProdTransId.index();
    public static final int OUTSUBLINEID = AttributesEnum.OutSublineId.index();
    public static final int SNO = AttributesEnum.Sno.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int SUBLINETYPE = AttributesEnum.SublineType.index();
    public static final int NOMACHINES = AttributesEnum.NoMachines.index();
    public static final int SUBLINENO = AttributesEnum.SublineNo.index();
    public static final int OPERATORABS = AttributesEnum.OperatorAbs.index();
    public static final int LINEOUTPUT = AttributesEnum.LineOutput.index();
    public static final int TARGETQTY = AttributesEnum.TargetQty.index();
    public static final int BALANCEQTY = AttributesEnum.BalanceQty.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int TEMPQTY = AttributesEnum.TempQty.index();
    public static final int RESPOST = AttributesEnum.ResPost.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SIZEQUANTITY = AttributesEnum.SizeQuantity.index();
    public static final int PRODQTY = AttributesEnum.ProdQty.index();
    public static final int PRODUCTIONQUANTITY = AttributesEnum.ProductionQuantity.index();
    public static final int PRVLINEOUTPUT = AttributesEnum.PrvLineoutput.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BPONO = AttributesEnum.BpoNo.index();
    public static final int SALEORDERID = AttributesEnum.SaleOrderId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int ERRORMESSAGE = AttributesEnum.ErrorMessage.index();
    public static final int LASTACTION = AttributesEnum.LastAction.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int PRODTYPE = AttributesEnum.ProdType.index();
    public static final int TOTREJECTION = AttributesEnum.TotRejection.index();
    public static final int DAYREJECTION = AttributesEnum.DayRejection.index();
    public static final int STNNUMBER = AttributesEnum.StnNumber.index();
    public static final int JOBNAME = AttributesEnum.JobName.index();
    public static final int DAYPRODUCTION = AttributesEnum.DayProduction.index();
    public static final int TOTALPRODUETION = AttributesEnum.TotalProduetion.index();
    public static final int TOTALINPUT = AttributesEnum.TotalInput.index();
    public static final int WIP = AttributesEnum.Wip.index();
    public static final int PRELINEOUTPUT = AttributesEnum.PreLineoutput.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int PRODUCEDMIN = AttributesEnum.ProducedMin.index();
    public static final int SAMVALUE = AttributesEnum.SamValue.index();
    public static final int SAM = AttributesEnum.Sam.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();
    public static final int TOTALPRO = AttributesEnum.TotalPro.index();
    public static final int PREVTOTALPRO = AttributesEnum.PrevTotalPro.index();
    public static final int PRVTARGETQTY = AttributesEnum.PrvTargetqty.index();
    public static final int BALANCEOUTPUT = AttributesEnum.BalanceOutput.index();
    public static final int BALANCETARGET = AttributesEnum.BalanceTarget.index();
    public static final int OPERATIONLINE = AttributesEnum.OperationLine.index();
    public static final int STNNO = AttributesEnum.StnNo.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int DETAILVO = AttributesEnum.DetailVO.index();
    public static final int SIZELOV1 = AttributesEnum.SizeLOV1.index();
    public static final int LINENOCODEVO1 = AttributesEnum.LineNoCodeVO1.index();
    public static final int BUYERLOVVO1 = AttributesEnum.BuyerLovVo1.index();
    public static final int PRODTYPEVO1 = AttributesEnum.ProdTypeVO1.index();
    public static final int PRODTYPENEWVO1 = AttributesEnum.ProdTypeNewVo1.index();
    public static final int SAM_LOV1 = AttributesEnum.Sam_LOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LineVORowImpl() {
    }

    /**
     * Gets LineVO entity object.
     * @return the LineVO
     */
    public LineEOImpl getLineVO() {
        return (LineEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DIVISION_ID using the alias name DivisionId.
     * @return the DIVISION_ID
     */
    public String getDivisionId() {
        return (String) getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for DIVISION_ID using the alias name DivisionId.
     * @param value value to set the DIVISION_ID
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for PROD_TRANS_ID using the alias name ProdTransId.
     * @return the PROD_TRANS_ID
     */
    public Number getProdTransId() {
        return (Number) getAttributeInternal(PRODTRANSID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_TRANS_ID using the alias name ProdTransId.
     * @param value value to set the PROD_TRANS_ID
     */
    public void setProdTransId(Number value) {
        setAttributeInternal(PRODTRANSID, value);
    }

    /**
     * Gets the attribute value for OUT_SUBLINE_ID using the alias name OutSublineId.
     * @return the OUT_SUBLINE_ID
     */
    public Number getOutSublineId() {
        return (Number) getAttributeInternal(OUTSUBLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for OUT_SUBLINE_ID using the alias name OutSublineId.
     * @param value value to set the OUT_SUBLINE_ID
     */
    public void setOutSublineId(Number value) {
        setAttributeInternal(OUTSUBLINEID, value);
    }

    /**
     * Gets the attribute value for SNO using the alias name Sno.
     * @return the SNO
     */
    public Number getSno() {
        return (Number) getAttributeInternal(SNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SNO using the alias name Sno.
     * @param value value to set the SNO
     */
    public void setSno(Number value) {
        setAttributeInternal(SNO, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public String getLineId() {
        return (String) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(String value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for SUBLINE_TYPE using the alias name SublineType.
     * @return the SUBLINE_TYPE
     */
    public String getSublineType() {
        return (String) getAttributeInternal(SUBLINETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBLINE_TYPE using the alias name SublineType.
     * @param value value to set the SUBLINE_TYPE
     */
    public void setSublineType(String value) {
        setAttributeInternal(SUBLINETYPE, value);
    }

    /**
     * Gets the attribute value for NO_MACHINES using the alias name NoMachines.
     * @return the NO_MACHINES
     */
    public Number getNoMachines() {
        return (Number) getAttributeInternal(NOMACHINES);
    }

    /**
     * Sets <code>value</code> as attribute value for NO_MACHINES using the alias name NoMachines.
     * @param value value to set the NO_MACHINES
     */
    public void setNoMachines(Number value) {
        setAttributeInternal(NOMACHINES, value);
    }

    /**
     * Gets the attribute value for SUBLINE_NO using the alias name SublineNo.
     * @return the SUBLINE_NO
     */
    public String getSublineNo() {
        return (String) getAttributeInternal(SUBLINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBLINE_NO using the alias name SublineNo.
     * @param value value to set the SUBLINE_NO
     */
    public void setSublineNo(String value) {
        setAttributeInternal(SUBLINENO, value);
    }

    /**
     * Gets the attribute value for OPERATOR_ABS using the alias name OperatorAbs.
     * @return the OPERATOR_ABS
     */
    public Number getOperatorAbs() {
        return (Number) getAttributeInternal(OPERATORABS);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATOR_ABS using the alias name OperatorAbs.
     * @param value value to set the OPERATOR_ABS
     */
    public void setOperatorAbs(Number value) {
        setAttributeInternal(OPERATORABS, value);
    }

    /**
     * Gets the attribute value for LINE_OUTPUT using the alias name LineOutput.
     * @return the LINE_OUTPUT
     */
    public Number getLineOutput() {
        return (Number) getAttributeInternal(LINEOUTPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_OUTPUT using the alias name LineOutput.
     * @param value value to set the LINE_OUTPUT
     */
    public void setLineOutput(Number value) {
        setAttributeInternal(LINEOUTPUT, value);
    }

    /**
     * Gets the attribute value for TARGET_QTY using the alias name TargetQty.
     * @return the TARGET_QTY
     */
    public Number getTargetQty() {
        return (Number) getAttributeInternal(TARGETQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TARGET_QTY using the alias name TargetQty.
     * @param value value to set the TARGET_QTY
     */
    public void setTargetQty(Number value) {
        setAttributeInternal(TARGETQTY, value);
    }

    /**
     * Gets the attribute value for BALANCE_QTY using the alias name BalanceQty.
     * @return the BALANCE_QTY
     */
    public Number getBalanceQty() {
        return (Number) getAttributeInternal(BALANCEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BALANCE_QTY using the alias name BalanceQty.
     * @param value value to set the BALANCE_QTY
     */
    public void setBalanceQty(Number value) {
        setAttributeInternal(BALANCEQTY, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for TEMP_QTY using the alias name TempQty.
     * @return the TEMP_QTY
     */
    public Number getTempQty() {
        return (Number) getAttributeInternal(TEMPQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_QTY using the alias name TempQty.
     * @param value value to set the TEMP_QTY
     */
    public void setTempQty(Number value) {
        setAttributeInternal(TEMPQTY, value);
    }

    /**
     * Gets the attribute value for RES_POST using the alias name ResPost.
     * @return the RES_POST
     */
    public String getResPost() {
        return (String) getAttributeInternal(RESPOST);
    }

    /**
     * Sets <code>value</code> as attribute value for RES_POST using the alias name ResPost.
     * @param value value to set the RES_POST
     */
    public void setResPost(String value) {
        setAttributeInternal(RESPOST, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SIZE_QUANTITY using the alias name SizeQuantity.
     * @return the SIZE_QUANTITY
     */
    public Number getSizeQuantity() {
        return (Number) getAttributeInternal(SIZEQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_QUANTITY using the alias name SizeQuantity.
     * @param value value to set the SIZE_QUANTITY
     */
    public void setSizeQuantity(Number value) {
        setAttributeInternal(SIZEQUANTITY, value);
    }

    /**
     * Gets the attribute value for PROD_QTY using the alias name ProdQty.
     * @return the PROD_QTY
     */
    public String getProdQty() {
        return (String) getAttributeInternal(PRODQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_QTY using the alias name ProdQty.
     * @param value value to set the PROD_QTY
     */
    public void setProdQty(String value) {
        setAttributeInternal(PRODQTY, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_QUANTITY using the alias name ProductionQuantity.
     * @return the PRODUCTION_QUANTITY
     */
    public String getProductionQuantity() {
        return (String) getAttributeInternal(PRODUCTIONQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_QUANTITY using the alias name ProductionQuantity.
     * @param value value to set the PRODUCTION_QUANTITY
     */
    public void setProductionQuantity(String value) {
        setAttributeInternal(PRODUCTIONQUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrvTargetqty.
     * @return the PrvTargetqty
     */
    public String getPrvTargetqty() {
        return (String) getAttributeInternal(PRVTARGETQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrvTargetqty.
     * @param value value to set the  PrvTargetqty
     */
    public void setPrvTargetqty(String value) {
        setAttributeInternal(PRVTARGETQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceOutput.
     * @return the BalanceOutput
     */
    public String getBalanceOutput() {
        return (String) getAttributeInternal(BALANCEOUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceOutput.
     * @param value value to set the  BalanceOutput
     */
    public void setBalanceOutput(String value) {
        setAttributeInternal(BALANCEOUTPUT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BalanceTarget.
     * @return the BalanceTarget
     */
    public String getBalanceTarget() {
        return (String) getAttributeInternal(BALANCETARGET);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BalanceTarget.
     * @param value value to set the  BalanceTarget
     */
    public void setBalanceTarget(String value) {
        setAttributeInternal(BALANCETARGET, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OperationLine.
     * @return the OperationLine
     */
    public String getOperationLine() {
        return (String) getAttributeInternal(OPERATIONLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OperationLine.
     * @param value value to set the  OperationLine
     */
    public void setOperationLine(String value) {
        setAttributeInternal(OPERATIONLINE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrvLineoutput.
     * @return the PrvLineoutput
     */
    public String getPrvLineoutput() {
        return (String) getAttributeInternal(PRVLINEOUTPUT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrvLineoutput.
     * @param value value to set the  PrvLineoutput
     */
    public void setPrvLineoutput(String value) {
        setAttributeInternal(PRVLINEOUTPUT, value);
    }


    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for BPO_NO using the alias name BpoNo.
     * @return the BPO_NO
     */
    public String getBpoNo() {
        return (String) getAttributeInternal(BPONO);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_NO using the alias name BpoNo.
     * @param value value to set the BPO_NO
     */
    public void setBpoNo(String value) {
        setAttributeInternal(BPONO, value);
    }

    /**
     * Gets the attribute value for STYLE using the alias name Style.
     * @return the STYLE
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE using the alias name Style.
     * @param value value to set the STYLE
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for SEASON using the alias name Season.
     * @return the SEASON
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON using the alias name Season.
     * @param value value to set the SEASON
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for SALE_ORDER_ID using the alias name SaleOrderId.
     * @return the SALE_ORDER_ID
     */
    public Number getSaleOrderId() {
        return (Number) getAttributeInternal(SALEORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_ORDER_ID using the alias name SaleOrderId.
     * @param value value to set the SALE_ORDER_ID
     */
    public void setSaleOrderId(Number value) {
        setAttributeInternal(SALEORDERID, value);
    }

    /**
     * Gets the attribute value for STN_NO using the alias name StnNo.
     * @return the STN_NO
     */
    public String getStnNo() {
        return (String) getAttributeInternal(STNNO);
    }

    /**
     * Sets <code>value</code> as attribute value for STN_NO using the alias name StnNo.
     * @param value value to set the STN_NO
     */
    public void setStnNo(String value) {
        setAttributeInternal(STNNO, value);
    }

    /**
     * Gets the attribute value for BPO_ID using the alias name BpoId.
     * @return the BPO_ID
     */
    public Number getBpoId() {
        return (Number) getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_ID using the alias name BpoId.
     * @param value value to set the BPO_ID
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for WASH using the alias name Wash.
     * @return the WASH
     */
    public String getWash() {
        return (String) getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH using the alias name Wash.
     * @param value value to set the WASH
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for PRODUCED_MIN using the alias name ProducedMin.
     * @return the PRODUCED_MIN
     */
    public Number getProducedMin() {
        return (Number) getAttributeInternal(PRODUCEDMIN);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCED_MIN using the alias name ProducedMin.
     * @param value value to set the PRODUCED_MIN
     */
    public void setProducedMin(Number value) {
        setAttributeInternal(PRODUCEDMIN, value);
    }

    /**
     * Gets the attribute value for SAM_VALUE using the alias name SamValue.
     * @return the SAM_VALUE
     */
    public Number getSamValue() {
        return (Number) getAttributeInternal(SAMVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM_VALUE using the alias name SamValue.
     * @param value value to set the SAM_VALUE
     */
    public void setSamValue(Number value) {
        setAttributeInternal(SAMVALUE, value);
    }

    /**
     * Gets the attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @return the ERROR_MESSAGE
     */
    public String getErrorMessage() {
        return (String) getAttributeInternal(ERRORMESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for ERROR_MESSAGE using the alias name ErrorMessage.
     * @param value value to set the ERROR_MESSAGE
     */
    public void setErrorMessage(String value) {
        setAttributeInternal(ERRORMESSAGE, value);
    }

    /**
     * Gets the attribute value for LAST_ACTION using the alias name LastAction.
     * @return the LAST_ACTION
     */
    public String getLastAction() {
        return (String) getAttributeInternal(LASTACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_ACTION using the alias name LastAction.
     * @param value value to set the LAST_ACTION
     */
    public void setLastAction(String value) {
        setAttributeInternal(LASTACTION, value);
    }

    /**
     * Gets the attribute value for PROD_TYPE using the alias name ProdType.
     * @return the PROD_TYPE
     */
    public String getProdType() {
        return (String) getAttributeInternal(PRODTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_TYPE using the alias name ProdType.
     * @param value value to set the PROD_TYPE
     */
    public void setProdType(String value) {
        setAttributeInternal(PRODTYPE, value);
    }

    /**
     * Gets the attribute value for TOT_REJECTION using the alias name TotRejection.
     * @return the TOT_REJECTION
     */
    public Number getTotRejection() {
        return (Number) getAttributeInternal(TOTREJECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_REJECTION using the alias name TotRejection.
     * @param value value to set the TOT_REJECTION
     */
    public void setTotRejection(Number value) {
        setAttributeInternal(TOTREJECTION, value);
    }

    /**
     * Gets the attribute value for DAY_REJECTION using the alias name DayRejection.
     * @return the DAY_REJECTION
     */
    public Number getDayRejection() {
        return (Number) getAttributeInternal(DAYREJECTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY_REJECTION using the alias name DayRejection.
     * @param value value to set the DAY_REJECTION
     */
    public void setDayRejection(Number value) {
        setAttributeInternal(DAYREJECTION, value);
    }

    /**
     * Gets the attribute value for STN_NUMBER using the alias name StnNumber.
     * @return the STN_NUMBER
     */
    public String getStnNumber() {
        return (String) getAttributeInternal(STNNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for STN_NUMBER using the alias name StnNumber.
     * @param value value to set the STN_NUMBER
     */
    public void setStnNumber(String value) {
        setAttributeInternal(STNNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute JobName.
     * @return the JobName
     */
    public String getJobName() {
        return (String) getAttributeInternal(JOBNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute JobName.
     * @param value value to set the  JobName
     */
    public void setJobName(String value) {
        setAttributeInternal(JOBNAME, value);
    }

    /**
     * Gets the attribute value for DAY_PRODUCTION using the alias name DayProduction.
     * @return the DAY_PRODUCTION
     */
    public Number getDayProduction() {
        return (Number) getAttributeInternal(DAYPRODUCTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DAY_PRODUCTION using the alias name DayProduction.
     * @param value value to set the DAY_PRODUCTION
     */
    public void setDayProduction(Number value) {
        setAttributeInternal(DAYPRODUCTION, value);
    }

    /**
     * Gets the attribute value for TOTAL_PRODUETION using the alias name TotalProduetion.
     * @return the TOTAL_PRODUETION
     */
    public Number getTotalProduetion() {
        return (Number) getAttributeInternal(TOTALPRODUETION);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_PRODUETION using the alias name TotalProduetion.
     * @param value value to set the TOTAL_PRODUETION
     */
    public void setTotalProduetion(Number value) {
        setAttributeInternal(TOTALPRODUETION, value);
    }

    /**
     * Gets the attribute value for TOTAL_INPUT using the alias name TotalInput.
     * @return the TOTAL_INPUT
     */
    public Number getTotalInput() {
        return (Number) getAttributeInternal(TOTALINPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_INPUT using the alias name TotalInput.
     * @param value value to set the TOTAL_INPUT
     */
    public void setTotalInput(Number value) {
        setAttributeInternal(TOTALINPUT, value);
    }

    /**
     * Gets the attribute value for WIP using the alias name Wip.
     * @return the WIP
     */
    public Number getWip() {
        return (Number) getAttributeInternal(WIP);
    }

    /**
     * Sets <code>value</code> as attribute value for WIP using the alias name Wip.
     * @param value value to set the WIP
     */
    public void setWip(Number value) {
        setAttributeInternal(WIP, value);
    }

    /**
     * Gets the attribute value for PRE_LINEOUTPUT using the alias name PreLineoutput.
     * @return the PRE_LINEOUTPUT
     */
    public Number getPreLineoutput() {
        return (Number) getAttributeInternal(PRELINEOUTPUT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRE_LINEOUTPUT using the alias name PreLineoutput.
     * @param value value to set the PRE_LINEOUTPUT
     */
    public void setPreLineoutput(Number value) {
        setAttributeInternal(PRELINEOUTPUT, value);
    }

    /**
     * Gets the attribute value for COLOR using the alias name Color.
     * @return the COLOR
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOR using the alias name Color.
     * @param value value to set the COLOR
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for SAM using the alias name Sam.
     * @return the SAM
     */
    public Number getSam() {
        return (Number) getAttributeInternal(SAM);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM using the alias name Sam.
     * @param value value to set the SAM
     */
    public void setSam(Number value) {
        setAttributeInternal(SAM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalPro.
     * @return the TotalPro
     */
    public Number getTotalPro() {
        return (Number) getAttributeInternal(TOTALPRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalPro.
     * @param value value to set the  TotalPro
     */
    public void setTotalPro(Number value) {
        setAttributeInternal(TOTALPRO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrevTotalPro.
     * @return the PrevTotalPro
     */
    public Number getPrevTotalPro() {
        return (Number) getAttributeInternal(PREVTOTALPRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrevTotalPro.
     * @param value value to set the  PrevTotalPro
     */
    public void setPrevTotalPro(Number value) {
        setAttributeInternal(PREVTOTALPRO, value);
    }

    /**
     * Gets the attribute value for JOB_ID using the alias name JobId.
     * @return the JOB_ID
     */
    public Number getJobId() {
        return (Number) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOB_ID using the alias name JobId.
     * @param value value to set the JOB_ID
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link DetailVO.
     */
    public Row getDetailVO() {
        return (Row)getAttributeInternal(DETAILVO);
    }

    /**
     * Sets the master-detail link DetailVO between this object and <code>value</code>.
     */
    public void setDetailVO(Row value) {
        setAttributeInternal(DETAILVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SizeLOV1.
     */
    public RowSet getSizeLOV1() {
        return (RowSet)getAttributeInternal(SIZELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LineNoCodeVO1.
     */
    public RowSet getLineNoCodeVO1() {
        return (RowSet)getAttributeInternal(LINENOCODEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BuyerLovVo1.
     */
    public RowSet getBuyerLovVo1() {
        return (RowSet)getAttributeInternal(BUYERLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProdTypeVO1.
     */
    public RowSet getProdTypeVO1() {
        return (RowSet)getAttributeInternal(PRODTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProdTypeNewVo1.
     */
    public RowSet getProdTypeNewVo1() {
        return (RowSet)getAttributeInternal(PRODTYPENEWVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Sam_LOV1.
     */
    public RowSet getSam_LOV1() {
        return (RowSet)getAttributeInternal(SAM_LOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
