package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 19 18:37:58 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class operationLineVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public operationLineVoImpl() {
    }
}
