package mnj.ont.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 04 15:37:36 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HederEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DivisionId {
            public Object get(HederEOImpl obj) {
                return obj.getDivisionId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setDivisionId((String)value);
            }
        }
        ,
        ProdTransId {
            public Object get(HederEOImpl obj) {
                return obj.getProdTransId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setProdTransId((Number)value);
            }
        }
        ,
        ProdTransNum {
            public Object get(HederEOImpl obj) {
                return obj.getProdTransNum();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setProdTransNum((Number)value);
            }
        }
        ,
        OutrecDate {
            public Object get(HederEOImpl obj) {
                return obj.getOutrecDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setOutrecDate((Date)value);
            }
        }
        ,
        SalesorderId {
            public Object get(HederEOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        SoLineId {
            public Object get(HederEOImpl obj) {
                return obj.getSoLineId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSoLineId((Number)value);
            }
        }
        ,
        JobId {
            public Object get(HederEOImpl obj) {
                return obj.getJobId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setJobId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(HederEOImpl obj) {
                return obj.getLineId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLineId((String)value);
            }
        }
        ,
        LineTarget {
            public Object get(HederEOImpl obj) {
                return obj.getLineTarget();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLineTarget((Number)value);
            }
        }
        ,
        Obno {
            public Object get(HederEOImpl obj) {
                return obj.getObno();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setObno((String)value);
            }
        }
        ,
        InseamId {
            public Object get(HederEOImpl obj) {
                return obj.getInseamId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setInseamId((String)value);
            }
        }
        ,
        Remarks {
            public Object get(HederEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(HederEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(HederEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        NewStyle {
            public Object get(HederEOImpl obj) {
                return obj.getNewStyle();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setNewStyle((String)value);
            }
        }
        ,
        OeSolineId {
            public Object get(HederEOImpl obj) {
                return obj.getOeSolineId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setOeSolineId((Number)value);
            }
        }
        ,
        CutIssueId {
            public Object get(HederEOImpl obj) {
                return obj.getCutIssueId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCutIssueId((Number)value);
            }
        }
        ,
        MoveStatus {
            public Object get(HederEOImpl obj) {
                return obj.getMoveStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setMoveStatus((String)value);
            }
        }
        ,
        PostedStatus {
            public Object get(HederEOImpl obj) {
                return obj.getPostedStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPostedStatus((String)value);
            }
        }
        ,
        TransactionStatus {
            public Object get(HederEOImpl obj) {
                return obj.getTransactionStatus();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTransactionStatus((String)value);
            }
        }
        ,
        Subinventory {
            public Object get(HederEOImpl obj) {
                return obj.getSubinventory();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setSubinventory((String)value);
            }
        }
        ,
        PostedStatusTmp {
            public Object get(HederEOImpl obj) {
                return obj.getPostedStatusTmp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setPostedStatusTmp((String)value);
            }
        }
        ,
        MoveStatusTmp {
            public Object get(HederEOImpl obj) {
                return obj.getMoveStatusTmp();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setMoveStatusTmp((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(HederEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(HederEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        JobQty {
            public Object get(HederEOImpl obj) {
                return obj.getJobQty();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setJobQty((Number)value);
            }
        }
        ,
        CustomerId {
            public Object get(HederEOImpl obj) {
                return obj.getCustomerId();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ,
        Style {
            public Object get(HederEOImpl obj) {
                return obj.getStyle();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Bpo {
            public Object get(HederEOImpl obj) {
                return obj.getBpo();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setBpo((String)value);
            }
        }
        ,
        BelancQty {
            public Object get(HederEOImpl obj) {
                return obj.getBelancQty();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setBelancQty((Number)value);
            }
        }
        ,
        DocNo {
            public Object get(HederEOImpl obj) {
                return obj.getDocNo();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setDocNo((String)value);
            }
        }
        ,
        TotalStandardMinutes {
            public Object get(HederEOImpl obj) {
                return obj.getTotalStandardMinutes();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTotalStandardMinutes((Number)value);
            }
        }
        ,
        TotalStandardMinutes1 {
            public Object get(HederEOImpl obj) {
                return obj.getTotalStandardMinutes1();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTotalStandardMinutes1((Number)value);
            }
        }
        ,
        Efficiency {
            public Object get(HederEOImpl obj) {
                return obj.getEfficiency();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setEfficiency((Number)value);
            }
        }
        ,
        TotalProducedMinutes {
            public Object get(HederEOImpl obj) {
                return obj.getTotalProducedMinutes();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTotalProducedMinutes((Number)value);
            }
        }
        ,
        TlStandardMin {
            public Object get(HederEOImpl obj) {
                return obj.getTlStandardMin();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setTlStandardMin((Number)value);
            }
        }
        ,
        LineVO {
            public Object get(HederEOImpl obj) {
                return obj.getLineVO();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AdditionBlockEO {
            public Object get(HederEOImpl obj) {
                return obj.getAdditionBlockEO();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjMfgOutputOffStandard {
            public Object get(HederEOImpl obj) {
                return obj.getMnjMfgOutputOffStandard();
            }

            public void put(HederEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HederEOImpl object);

        public abstract void put(HederEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DIVISIONID = AttributesEnum.DivisionId.index();
    public static final int PRODTRANSID = AttributesEnum.ProdTransId.index();
    public static final int PRODTRANSNUM = AttributesEnum.ProdTransNum.index();
    public static final int OUTRECDATE = AttributesEnum.OutrecDate.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int SOLINEID = AttributesEnum.SoLineId.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int LINETARGET = AttributesEnum.LineTarget.index();
    public static final int OBNO = AttributesEnum.Obno.index();
    public static final int INSEAMID = AttributesEnum.InseamId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int NEWSTYLE = AttributesEnum.NewStyle.index();
    public static final int OESOLINEID = AttributesEnum.OeSolineId.index();
    public static final int CUTISSUEID = AttributesEnum.CutIssueId.index();
    public static final int MOVESTATUS = AttributesEnum.MoveStatus.index();
    public static final int POSTEDSTATUS = AttributesEnum.PostedStatus.index();
    public static final int TRANSACTIONSTATUS = AttributesEnum.TransactionStatus.index();
    public static final int SUBINVENTORY = AttributesEnum.Subinventory.index();
    public static final int POSTEDSTATUSTMP = AttributesEnum.PostedStatusTmp.index();
    public static final int MOVESTATUSTMP = AttributesEnum.MoveStatusTmp.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int JOBQTY = AttributesEnum.JobQty.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int BPO = AttributesEnum.Bpo.index();
    public static final int BELANCQTY = AttributesEnum.BelancQty.index();
    public static final int DOCNO = AttributesEnum.DocNo.index();
    public static final int TOTALSTANDARDMINUTES = AttributesEnum.TotalStandardMinutes.index();
    public static final int TOTALSTANDARDMINUTES1 = AttributesEnum.TotalStandardMinutes1.index();
    public static final int EFFICIENCY = AttributesEnum.Efficiency.index();
    public static final int TOTALPRODUCEDMINUTES = AttributesEnum.TotalProducedMinutes.index();
    public static final int TLSTANDARDMIN = AttributesEnum.TlStandardMin.index();
    public static final int LINEVO = AttributesEnum.LineVO.index();
    public static final int ADDITIONBLOCKEO = AttributesEnum.AdditionBlockEO.index();
    public static final int MNJMFGOUTPUTOFFSTANDARD = AttributesEnum.MnjMfgOutputOffStandard.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HederEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.HederEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for DivisionId, using the alias name DivisionId.
     * @return the DivisionId
     */
    public String getDivisionId() {
        return (String)getAttributeInternal(DIVISIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DivisionId.
     * @param value value to set the DivisionId
     */
    public void setDivisionId(String value) {
        setAttributeInternal(DIVISIONID, value);
    }

    /**
     * Gets the attribute value for ProdTransId, using the alias name ProdTransId.
     * @return the ProdTransId
     */
    public Number getProdTransId() {
        return (Number)getAttributeInternal(PRODTRANSID);
    }


    /**
     * Sets <code>value</code> as the attribute value for ProdTransId.
     * @param value value to set the ProdTransId
     */
    public void setProdTransId(Number value) {
        setAttributeInternal(PRODTRANSID, value);
    }

    /**
     * Gets the attribute value for ProdTransNum, using the alias name ProdTransNum.
     * @return the ProdTransNum
     */
    public Number getProdTransNum() {
        return (Number)getAttributeInternal(PRODTRANSNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdTransNum.
     * @param value value to set the ProdTransNum
     */
    public void setProdTransNum(Number value) {
        setAttributeInternal(PRODTRANSNUM, value);
    }

    /**
     * Gets the attribute value for OutrecDate, using the alias name OutrecDate.
     * @return the OutrecDate
     */
    public Date getOutrecDate() {
        return (Date)getAttributeInternal(OUTRECDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OutrecDate.
     * @param value value to set the OutrecDate
     */
    public void setOutrecDate(Date value) {
        setAttributeInternal(OUTRECDATE, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for SoLineId, using the alias name SoLineId.
     * @return the SoLineId
     */
    public Number getSoLineId() {
        return (Number)getAttributeInternal(SOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SoLineId.
     * @param value value to set the SoLineId
     */
    public void setSoLineId(Number value) {
        setAttributeInternal(SOLINEID, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the JobId
     */
    public Number getJobId() {
        return (Number)getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(Number value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public String getLineId() {
        return (String)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(String value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for LineTarget, using the alias name LineTarget.
     * @return the LineTarget
     */
    public Number getLineTarget() {
        return (Number)getAttributeInternal(LINETARGET);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineTarget.
     * @param value value to set the LineTarget
     */
    public void setLineTarget(Number value) {
        setAttributeInternal(LINETARGET, value);
    }

    /**
     * Gets the attribute value for Obno, using the alias name Obno.
     * @return the Obno
     */
    public String getObno() {
        return (String)getAttributeInternal(OBNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Obno.
     * @param value value to set the Obno
     */
    public void setObno(String value) {
        setAttributeInternal(OBNO, value);
    }

    /**
     * Gets the attribute value for InseamId, using the alias name InseamId.
     * @return the InseamId
     */
    public String getInseamId() {
        return (String)getAttributeInternal(INSEAMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InseamId.
     * @param value value to set the InseamId
     */
    public void setInseamId(String value) {
        setAttributeInternal(INSEAMID, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for NewStyle, using the alias name NewStyle.
     * @return the NewStyle
     */
    public String getNewStyle() {
        return (String)getAttributeInternal(NEWSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewStyle.
     * @param value value to set the NewStyle
     */
    public void setNewStyle(String value) {
        setAttributeInternal(NEWSTYLE, value);
    }

    /**
     * Gets the attribute value for OeSolineId, using the alias name OeSolineId.
     * @return the OeSolineId
     */
    public Number getOeSolineId() {
        return (Number)getAttributeInternal(OESOLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OeSolineId.
     * @param value value to set the OeSolineId
     */
    public void setOeSolineId(Number value) {
        setAttributeInternal(OESOLINEID, value);
    }

    /**
     * Gets the attribute value for CutIssueId, using the alias name CutIssueId.
     * @return the CutIssueId
     */
    public Number getCutIssueId() {
        return (Number)getAttributeInternal(CUTISSUEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CutIssueId.
     * @param value value to set the CutIssueId
     */
    public void setCutIssueId(Number value) {
        setAttributeInternal(CUTISSUEID, value);
    }

    /**
     * Gets the attribute value for MoveStatus, using the alias name MoveStatus.
     * @return the MoveStatus
     */
    public String getMoveStatus() {
        return (String)getAttributeInternal(MOVESTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for MoveStatus.
     * @param value value to set the MoveStatus
     */
    public void setMoveStatus(String value) {
        setAttributeInternal(MOVESTATUS, value);
    }

    /**
     * Gets the attribute value for PostedStatus, using the alias name PostedStatus.
     * @return the PostedStatus
     */
    public String getPostedStatus() {
        return (String)getAttributeInternal(POSTEDSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatus.
     * @param value value to set the PostedStatus
     */
    public void setPostedStatus(String value) {
        setAttributeInternal(POSTEDSTATUS, value);
    }

    /**
     * Gets the attribute value for TransactionStatus, using the alias name TransactionStatus.
     * @return the TransactionStatus
     */
    public String getTransactionStatus() {
        return (String)getAttributeInternal(TRANSACTIONSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TransactionStatus.
     * @param value value to set the TransactionStatus
     */
    public void setTransactionStatus(String value) {
        setAttributeInternal(TRANSACTIONSTATUS, value);
    }

    /**
     * Gets the attribute value for Subinventory, using the alias name Subinventory.
     * @return the Subinventory
     */
    public String getSubinventory() {
        return (String)getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Subinventory.
     * @param value value to set the Subinventory
     */
    public void setSubinventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for PostedStatusTmp, using the alias name PostedStatusTmp.
     * @return the PostedStatusTmp
     */
    public String getPostedStatusTmp() {
        return (String)getAttributeInternal(POSTEDSTATUSTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostedStatusTmp.
     * @param value value to set the PostedStatusTmp
     */
    public void setPostedStatusTmp(String value) {
        setAttributeInternal(POSTEDSTATUSTMP, value);
    }

    /**
     * Gets the attribute value for MoveStatusTmp, using the alias name MoveStatusTmp.
     * @return the MoveStatusTmp
     */
    public String getMoveStatusTmp() {
        return (String)getAttributeInternal(MOVESTATUSTMP);
    }

    /**
     * Sets <code>value</code> as the attribute value for MoveStatusTmp.
     * @param value value to set the MoveStatusTmp
     */
    public void setMoveStatusTmp(String value) {
        setAttributeInternal(MOVESTATUSTMP, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for JobQty, using the alias name JobQty.
     * @return the JobQty
     */
    public Number getJobQty() {
        return (Number)getAttributeInternal(JOBQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobQty.
     * @param value value to set the JobQty
     */
    public void setJobQty(Number value) {
        setAttributeInternal(JOBQTY, value);
    }

    /**
     * Gets the attribute value for CustomerId, using the alias name CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number)getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CustomerId.
     * @param value value to set the CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for Style, using the alias name Style.
     * @return the Style
     */
    public String getStyle() {
        return (String)getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Style.
     * @param value value to set the Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for Bpo, using the alias name Bpo.
     * @return the Bpo
     */
    public String getBpo() {
        return (String)getAttributeInternal(BPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bpo.
     * @param value value to set the Bpo
     */
    public void setBpo(String value) {
        setAttributeInternal(BPO, value);
    }

    /**
     * Gets the attribute value for BelancQty, using the alias name BelancQty.
     * @return the BelancQty
     */
    public Number getBelancQty() {
        return (Number)getAttributeInternal(BELANCQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for BelancQty.
     * @param value value to set the BelancQty
     */
    public void setBelancQty(Number value) {
        setAttributeInternal(BELANCQTY, value);
    }

    /**
     * Gets the attribute value for DocNo, using the alias name DocNo.
     * @return the DocNo
     */
    public String getDocNo() {
        return (String)getAttributeInternal(DOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocNo.
     * @param value value to set the DocNo
     */
    public void setDocNo(String value) {
        setAttributeInternal(DOCNO, value);
    }

    /**
     * Gets the attribute value for TotalStandardMinutes, using the alias name TotalStandardMinutes.
     * @return the TotalStandardMinutes
     */
    public Number getTotalStandardMinutes() {
        return (Number)getAttributeInternal(TOTALSTANDARDMINUTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalStandardMinutes.
     * @param value value to set the TotalStandardMinutes
     */
    public void setTotalStandardMinutes(Number value) {
        setAttributeInternal(TOTALSTANDARDMINUTES, value);
    }

    /**
     * Gets the attribute value for TotalStandardMinutes1, using the alias name TotalStandardMinutes1.
     * @return the TotalStandardMinutes1
     */
    public Number getTotalStandardMinutes1() {
        return (Number)getAttributeInternal(TOTALSTANDARDMINUTES1);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalStandardMinutes1.
     * @param value value to set the TotalStandardMinutes1
     */
    public void setTotalStandardMinutes1(Number value) {
        setAttributeInternal(TOTALSTANDARDMINUTES1, value);
    }

    /**
     * Gets the attribute value for Efficiency, using the alias name Efficiency.
     * @return the Efficiency
     */
    public Number getEfficiency() {
        return (Number)getAttributeInternal(EFFICIENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Efficiency.
     * @param value value to set the Efficiency
     */
    public void setEfficiency(Number value) {
        setAttributeInternal(EFFICIENCY, value);
    }

    /**
     * Gets the attribute value for TotalProducedMinutes, using the alias name TotalProducedMinutes.
     * @return the TotalProducedMinutes
     */
    public Number getTotalProducedMinutes() {
        return (Number)getAttributeInternal(TOTALPRODUCEDMINUTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalProducedMinutes.
     * @param value value to set the TotalProducedMinutes
     */
    public void setTotalProducedMinutes(Number value) {
        setAttributeInternal(TOTALPRODUCEDMINUTES, value);
    }

    /**
     * Gets the attribute value for TlStandardMin, using the alias name TlStandardMin.
     * @return the TlStandardMin
     */
    public Number getTlStandardMin() {
        return (Number)getAttributeInternal(TLSTANDARDMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for TlStandardMin.
     * @param value value to set the TlStandardMin
     */
    public void setTlStandardMin(Number value) {
        setAttributeInternal(TLSTANDARDMIN, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getLineVO() {
        return (RowIterator)getAttributeInternal(LINEVO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getAdditionBlockEO() {
        return (RowIterator)getAttributeInternal(ADDITIONBLOCKEO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjMfgOutputOffStandard() {
        return (RowIterator)getAttributeInternal(MNJMFGOUTPUTOFFSTANDARD);
    }


    /**
     * @param prodTransId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number prodTransId) {
        return new Key(new Object[]{prodTransId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        Integer empno =Integer.parseInt(new oracle.jbo.server.SequenceImpl("MNJ_MFG_LINEOUTPUT_S", getDBTransaction()).getSequenceNumber().toString());
           oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_LINEOUTPUT_S",getDBTransaction());
           oracle.jbo.domain.Number sVal = s.getSequenceNumber();
           setProdTransId(sVal);
           //cust_mnj_ont_pkg.cust_mnj_packassort_srno
  
    }


    public String getSrNoString() {
          String srno = null;
          String stmt = "BEGIN :1 := mnj_mfg_doc_no_pkg.stitch_lin_output; end;";
          java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
          try {
              cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
              cs.execute();
              srno = cs.getString(1);
              cs.close();
          } catch (Exception e) {
              e.printStackTrace();
          }
          return srno;
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        Map sessionScope = ADFContext.getCurrent().getSessionScope();   
        String user = (String)sessionScope.get("userId");
        String orgId  =(String)sessionScope.get("orgId");
        String unitName  =(String)sessionScope.get("unitName");
       
        System.out.println("Inquiry information DO DML 1 ------------------>"+user);
        System.out.println("Inquiry information DO DML 2------------------>"+orgId);
        System.out.println("Inquiry information DO DML 3 ------------------>"+unitName);
        
        if(DML_UPDATE == operation){
                  try {
                      setLastUpdateDate((Date)Date.getCurrentDate()); 
                      setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                  } catch (SQLException f) {
                      System.out.println(f.getMessage());
                  }
              }
              else if (DML_INSERT == operation){
               
                  try {
                     
                      setDivisionId(orgId);
                      setAttribute1(unitName);
                      setDocNo(getSrNoString());
                      setCreationDate((Date)Date.getCurrentDate());  
                      setCreatedBy(new oracle.jbo.domain.Number(user));
                     
                  } catch (SQLException f) {
                      ;
                  }
              }
        
        super.doDML(operation, e);
    }
}
